### ISSUE TITLE
Variable names such as l, o violate Flake8

### ISSUE THREAD

**Issue by kapoorlab** [KietzmannLab/BLT-pytorch-CCN23#1]
Hello, 

Just a minor issue to bring to your attention in using variable names, while running pre-commit checks Flake8 complaint about 'E741 ambiguous variable name 'l'' coming from two instances in the model definition : https://github.com/KietzmannLab/BLT-pytorch-CCN23/blob/7e801e0cd7d9c78f05413aa03a18acb0eabdd9e4/BLT_train/models/BLT_net.py#L118

[It violates PEP naming conventions](https://peps.python.org/pep-0008/#names-to-avoid).

Cheers,
Varun

**Comment by novelmartis** [comment]
interesting. This is the first time I am hearing about PEP. Also, this seems to be a cosmetic issue no? In any case, when we write the code next time, I'll use better variable names anyway. maybe 'iter' is always an option in such cases. Thanks for noticing this.
